// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeInvite = `-- name: ConsumeInvite :exec
UPDATE invites SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeInvite, id)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (user_id, token_hash, passcode_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, passcode_hash, invited_by, expires_at, consumed_at, created_at
`

type CreateInviteParams struct {
	UserID       uuid.UUID
	TokenHash    string
	PasscodeHash string
	InvitedBy    *uuid.UUID
	ExpiresAt    time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.UserID,
		arg.TokenHash,
		arg.PasscodeHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.PasscodeHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, family_id, expires_at, revoked_at, user_agent, ip, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	UserAgent string
	Ip        string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const expireOpenInvitesForUser = `-- name: ExpireOpenInvitesForUser :exec
UPDATE invites SET consumed_at = now() WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) ExpireOpenInvitesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireOpenInvitesForUser, userID)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, user_id, token_hash, passcode_hash, invited_by, expires_at, consumed_at, created_at FROM invites WHERE token_hash = $1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.PasscodeHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, expires_at, revoked_at, user_agent, ip, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
