// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeHiddenByUnit = `-- name: ActiveHiddenByUnit :one
SELECT id
FROM residents
WHERE status = 'active' AND directory_opt_in = FALSE AND is_primary = TRUE AND unit_number = $1
LIMIT 1
`

func (q *Queries) ActiveHiddenByUnit(ctx context.Context, unitNumber string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, activeHiddenByUnit, unitNumber)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteConversationsForUser = `-- name: DeleteConversationsForUser :exec
DELETE FROM conversations
WHERE user_low = $1 OR user_high = $1
`

func (q *Queries) DeleteConversationsForUser(ctx context.Context, userLow uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationsForUser, userLow)
	return err
}

const findConversation = `-- name: FindConversation :one
SELECT id, user_low, user_high, status, requested_by, created_at, updated_at
FROM conversations
WHERE user_low = $1 AND user_high = $2
`

type FindConversationParams struct {
	UserLow  uuid.UUID
	UserHigh uuid.UUID
}

func (q *Queries) FindConversation(ctx context.Context, arg FindConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findConversation, arg.UserLow, arg.UserHigh)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserLow,
		&i.UserHigh,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_low, user_high, status, requested_by, created_at, updated_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserLow,
		&i.UserHigh,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserContact = `-- name: GetUserContact :one
SELECT id, unit_number, display_name, directory_opt_in, status
FROM residents
WHERE id = $1
`

type GetUserContactRow struct {
	ID             uuid.UUID
	UnitNumber     string
	DisplayName    string
	DirectoryOptIn bool
	Status         string
}

func (q *Queries) GetUserContact(ctx context.Context, id uuid.UUID) (GetUserContactRow, error) {
	row := q.db.QueryRow(ctx, getUserContact, id)
	var i GetUserContactRow
	err := row.Scan(
		&i.ID,
		&i.UnitNumber,
		&i.DisplayName,
		&i.DirectoryOptIn,
		&i.Status,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations (user_low, user_high, status, requested_by)
VALUES ($1, $2, $3, $4)
RETURNING id, user_low, user_high, status, requested_by, created_at, updated_at
`

type InsertConversationParams struct {
	UserLow     uuid.UUID
	UserHigh    uuid.UUID
	Status      string
	RequestedBy uuid.UUID
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, insertConversation,
		arg.UserLow,
		arg.UserHigh,
		arg.Status,
		arg.RequestedBy,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserLow,
		&i.UserHigh,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDirectMessage = `-- name: InsertDirectMessage :one
INSERT INTO direct_messages (conversation_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, body, created_at
`

type InsertDirectMessageParams struct {
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Body           string
}

func (q *Queries) InsertDirectMessage(ctx context.Context, arg InsertDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, insertDirectMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT
    c.id, c.user_low, c.user_high, c.status, c.requested_by, c.created_at, c.updated_at,
    m.body AS last_message
FROM conversations c
JOIN LATERAL (
    SELECT body
    FROM direct_messages
    WHERE conversation_id = c.id
    ORDER BY created_at DESC
    LIMIT 1
) m ON TRUE
WHERE (c.user_low = $1 OR c.user_high = $1)
  AND (c.status <> 'declined' OR c.requested_by = $1)
  AND NOT EXISTS (
    SELECT 1 FROM users AS peer
    WHERE peer.id = CASE WHEN c.user_low = $1 THEN c.user_high ELSE c.user_low END
      AND peer.status = 'inactive'
      AND peer.directory_opt_in = FALSE
  )
ORDER BY c.updated_at DESC
`

type ListConversationsForUserRow struct {
	ID          uuid.UUID
	UserLow     uuid.UUID
	UserHigh    uuid.UUID
	Status      string
	RequestedBy uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastMessage string
}

func (q *Queries) ListConversationsForUser(ctx context.Context, userLow uuid.UUID) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, userLow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsForUserRow{}
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserLow,
			&i.UserHigh,
			&i.Status,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectMessages = `-- name: ListDirectMessages :many
SELECT id, conversation_id, sender_id, body, created_at
FROM direct_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDirectMessages(ctx context.Context, conversationID uuid.UUID) ([]DirectMessage, error) {
	rows, err := q.db.Query(ctx, listDirectMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectMessage{}
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationState = `-- name: SetConversationState :one
UPDATE conversations
SET status = $2, requested_by = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_low, user_high, status, requested_by, created_at, updated_at
`

type SetConversationStateParams struct {
	ID          uuid.UUID
	Status      string
	RequestedBy uuid.UUID
}

func (q *Queries) SetConversationState(ctx context.Context, arg SetConversationStateParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationState, arg.ID, arg.Status, arg.RequestedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserLow,
		&i.UserHigh,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
