// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbq

import (
	"time"

	"github.com/google/uuid"
)

type Invite struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TokenHash    string
	PasscodeHash string
	InvitedBy    *uuid.UUID
	ExpiresAt    time.Time
	ConsumedAt   *time.Time
	CreatedAt    time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	UserAgent string
	Ip        string
	CreatedAt time.Time
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
	UpdatedBy *uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	UnitNumber     string
	DisplayName    string
	PasswordHash   *string
	IsAdmin        bool
	Status         string
	DirectoryOptIn bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeactivatedAt  *time.Time
}
