// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbq

import (
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID          uuid.UUID
	UserLow     uuid.UUID
	UserHigh    uuid.UUID
	Status      string
	RequestedBy uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DirectMessage struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Body           string
	CreatedAt      time.Time
}

type Invite struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TokenHash    string
	PasscodeHash string
	InvitedBy    *uuid.UUID
	ExpiresAt    time.Time
	ConsumedAt   *time.Time
	CreatedAt    time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	FamilyID  uuid.UUID
	ExpiresAt time.Time
	RevokedAt *time.Time
	UserAgent string
	Ip        string
	CreatedAt time.Time
}

type Resident struct {
	ID             uuid.UUID
	Email          string
	UnitNumber     string
	UnitID         uuid.UUID
	IsPrimary      bool
	DisplayName    string
	PasswordHash   *string
	IsAdmin        bool
	Status         string
	DirectoryOptIn bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeactivatedAt  *time.Time
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
	UpdatedBy *uuid.UUID
}

type Unit struct {
	ID        uuid.UUID
	Number    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	DisplayName    string
	PasswordHash   *string
	IsAdmin        bool
	Status         string
	DirectoryOptIn bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeactivatedAt  *time.Time
	UnitID         uuid.UUID
	IsPrimary      bool
}
