// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET password_hash = $2, display_name = $3, status = 'active', updated_at = now()
WHERE id = $1
RETURNING id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at
`

type ActivateUserParams struct {
	ID           uuid.UUID
	PasswordHash *string
	DisplayName  string
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, arg.ID, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE is_admin = TRUE AND status = 'active'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActiveUser = `-- name: CreateActiveUser :one
INSERT INTO users (email, unit_number, display_name, password_hash, is_admin, status)
VALUES ($1, $2, $3, $4, $5, 'active')
RETURNING id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at
`

type CreateActiveUserParams struct {
	Email        string
	UnitNumber   string
	DisplayName  string
	PasswordHash *string
	IsAdmin      bool
}

func (q *Queries) CreateActiveUser(ctx context.Context, arg CreateActiveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createActiveUser,
		arg.Email,
		arg.UnitNumber,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (email, unit_number, display_name, is_admin, status)
VALUES ($1, $2, $3, $4, 'invited')
RETURNING id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at
`

type CreateInvitedUserParams struct {
	Email       string
	UnitNumber  string
	DisplayName string
	IsAdmin     bool
}

func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createInvitedUser,
		arg.Email,
		arg.UnitNumber,
		arg.DisplayName,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const listDirectory = `-- name: ListDirectory :many
SELECT id, unit_number, display_name, email
FROM users
WHERE status = 'active' AND directory_opt_in = TRUE
ORDER BY unit_number, display_name
`

type ListDirectoryRow struct {
	ID          uuid.UUID
	UnitNumber  string
	DisplayName string
	Email       string
}

func (q *Queries) ListDirectory(ctx context.Context) ([]ListDirectoryRow, error) {
	rows, err := q.db.Query(ctx, listDirectory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectoryRow{}
	for rows.Next() {
		var i ListDirectoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitNumber,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at FROM users ORDER BY unit_number, display_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.UnitNumber,
			&i.DisplayName,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.Status,
			&i.DirectoryOptIn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :one
UPDATE users SET is_admin = $2, updated_at = now() WHERE id = $1 RETURNING id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at
`

type SetUserAdminParams struct {
	ID      uuid.UUID
	IsAdmin bool
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users
SET status = $2,
    deactivated_at = CASE WHEN $2 = 'inactive' THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at
`

type SetUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2, directory_opt_in = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, unit_number, display_name, password_hash, is_admin, status, directory_opt_in, created_at, updated_at, deactivated_at
`

type UpdateUserProfileParams struct {
	ID             uuid.UUID
	DisplayName    string
	DirectoryOptIn bool
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.DirectoryOptIn)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnitNumber,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Status,
		&i.DirectoryOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}
