// Package db owns the Postgres pool and migrations. Queries are generated by
// sqlc into package dbq from internal/db/queries/*.sql.
package db

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"io/fs"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Open connects a pgx pool and pings it.
func Open(ctx context.Context, url string, maxConns int32) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, fmt.Errorf("parse DATABASE_URL: %w", err)
	}
	cfg.MaxConns = maxConns
	cfg.MaxConnIdleTime = 5 * time.Minute
	cfg.ConnConfig.ConnectTimeout = 5 * time.Second

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("open pool: %w", err)
	}
	pingCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping: %w", err)
	}
	return pool, nil
}

func provider(pool *pgxpool.Pool) (*goose.Provider, *sql.DB, error) {
	sqlDB := stdlib.OpenDBFromPool(pool)
	sub, err := fs.Sub(migrations, "migrations")
	if err != nil {
		sqlDB.Close()
		return nil, nil, err
	}
	p, err := goose.NewProvider(goose.DialectPostgres, sqlDB, sub)
	if err != nil {
		sqlDB.Close()
		return nil, nil, err
	}
	return p, sqlDB, nil
}

// Migrate applies pending embedded migrations. It refuses to run against a
// database that is ahead of this binary.
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	p, sqlDB, err := provider(pool)
	if err != nil {
		return err
	}
	defer sqlDB.Close()

	cur, err := p.GetDBVersion(ctx)
	if err != nil {
		return err
	}
	srcs := p.ListSources()
	if n := len(srcs); n > 0 && cur > srcs[n-1].Version {
		return fmt.Errorf("database schema version %d is newer than this binary supports (%d); upgrade the server", cur, srcs[n-1].Version)
	}
	_, err = p.Up(ctx)
	return err
}

// Pending reports whether the DB is behind the embedded migrations.
func Pending(ctx context.Context, pool *pgxpool.Pool) (bool, error) {
	p, sqlDB, err := provider(pool)
	if err != nil {
		return false, err
	}
	defer sqlDB.Close()
	ok, err := p.HasPending(ctx)
	return ok, err
}
